/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment2;

import java.util.ArrayList;
import java.util.ListIterator;
import javax.swing.JOptionPane;

/**
 *
 * @author Aditi
 */
public class JFrame_Modify extends javax.swing.JFrame {

    /**
     * Creates new form JFrame_Modify
     */
    
    private ArrayList<student> s;
    private ListIterator it;
    private String prevC;
    
    public JFrame_Modify(ArrayList<student> s1,ListIterator litr) {
        s = s1;
        it = litr;
        initComponents();
        setDetails();
        prevC = course.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        courseRadioButton = new javax.swing.JRadioButton();
        rollRadioButton = new javax.swing.JRadioButton();
        nameRadioButton = new javax.swing.JRadioButton();
        deptRadioButton = new javax.swing.JRadioButton();
        speRadioButton = new javax.swing.JRadioButton();
        regRadioButton = new javax.swing.JRadioButton();
        CGPARadioButton = new javax.swing.JRadioButton();
        creRadioButton = new javax.swing.JRadioButton();
        thesisRadioButton = new javax.swing.JRadioButton();
        yearRadioButton = new javax.swing.JRadioButton();
        course = new javax.swing.JTextField();
        roll = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        dept = new javax.swing.JTextField();
        spe = new javax.swing.JTextField();
        reg = new javax.swing.JTextField();
        CGPA = new javax.swing.JTextField();
        cre = new javax.swing.JTextField();
        thesis = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "MODIFY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Select Field To Be Modified:");

        courseRadioButton.setText("Course");
        courseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseRadioButtonActionPerformed(evt);
            }
        });

        rollRadioButton.setText("Roll Number");
        rollRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rollRadioButtonActionPerformed(evt);
            }
        });

        nameRadioButton.setText("Name");

        deptRadioButton.setText("Department");
        deptRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptRadioButtonActionPerformed(evt);
            }
        });

        speRadioButton.setText("Specialization");
        speRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speRadioButtonActionPerformed(evt);
            }
        });

        regRadioButton.setText("Period of Registration");
        regRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regRadioButtonActionPerformed(evt);
            }
        });

        CGPARadioButton.setText("CGPA");
        CGPARadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGPARadioButtonActionPerformed(evt);
            }
        });

        creRadioButton.setText("Credits");
        creRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creRadioButtonActionPerformed(evt);
            }
        });

        thesisRadioButton.setText("Thesis Area");

        yearRadioButton.setText("Year of Conformation");

        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });

        CGPA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CGPAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(creRadioButton, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(yearRadioButton)
                                .addGap(52, 52, 52)
                                .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(thesisRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(thesis, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(cre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(CGPARadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(CGPA, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(regRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(speRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(spe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(deptRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(nameRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(rollRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(roll, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(courseRadioButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(43, 43, 43))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(courseRadioButton)
                    .addComponent(course, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rollRadioButton)
                    .addComponent(roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameRadioButton)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptRadioButton)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(speRadioButton)
                    .addComponent(spe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regRadioButton)
                    .addComponent(reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CGPARadioButton)
                    .addComponent(CGPA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creRadioButton)
                    .addComponent(cre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thesisRadioButton)
                    .addComponent(thesis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearRadioButton)
                    .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("Done");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(okButton)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okButton)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rollRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rollRadioButtonActionPerformed

    private void CGPARadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGPARadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CGPARadioButtonActionPerformed

    private void CGPAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CGPAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CGPAActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        
        it.previous();
        student s1 = (student)it.next();
        try{
        if(rollRadioButton.isSelected())
        {
            if(roll.getText().equals(""))
                throw new EmptyFieldException("Empty Roll Field");
            s1.setRoll(roll.getText());
        }
        if(nameRadioButton.isSelected())
        {
            if(name.getText().equals(""))
                throw new EmptyFieldException("Empty Name Field");
            s1.setName(name.getText());
        }
        if(deptRadioButton.isSelected())
        {
            if(dept.getText().equals(""))
                throw new EmptyFieldException("Empty Department Field");
            s1.setDept(dept.getText());
        }
        if(speRadioButton.isSelected())
        {
            if(spe.getText().equals(""))
                throw new EmptyFieldException("Empty Specialization Field");
            s1.setSpe(spe.getText());
        }
        if(regRadioButton.isSelected())
        {
            if(reg.getText().equals(""))
                throw new EmptyFieldException("Empty Registration Period Field");
            s1.setReg(Integer.parseInt(reg.getText()));
        }
        if(CGPARadioButton.isSelected())
        {
            if(CGPA.getText().equals(""))
                throw new EmptyFieldException("Empty CGPA Field");
            s1.setCGPA(Integer.parseInt(CGPA.getText()));
        }
        if(creRadioButton.isSelected())
        {
            if(cre.getText().equals(""))
                throw new EmptyFieldException("Empty Credits Field");
            s1.setCredits(Integer.parseInt(cre.getText()));
        }
        if(thesisRadioButton.isSelected())
        {
            if(thesis.getText().equals(""))
                throw new EmptyFieldException("Empty Thesis Area Field");
            s1.setThesis(thesis.getText());
        }
        if(yearRadioButton.isSelected())
        {
            if(year.getText().equals(""))
                throw new EmptyFieldException("Empty Year Field");
            s1.setYear(Integer.parseInt(year.getText()));
        }
        if(courseRadioButton.isSelected()&&!course.getText().equals(""))
        {
            s1.setCourse(course.getText());
            s1 = setStudent();
        }
        s1.setGradStatus();
        it.previous();
        callJFrame1(it);
        }
        catch(NumberFormatException e)
        {
            JOptionPane.showMessageDialog(this,"Input Error - Unknown input found instead of an Integer");
        }
        catch(EmptyFieldException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        catch(InvalidCourseException e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private student setStudent()throws InvalidCourseException
    {
        String c = course.getText();
        student s1 = null;
        if(c.equals("UG"))
        {
            UG ug = new UG(c, roll.getText(), name.getText(), dept.getText(), Integer.parseInt(reg.getText()), Integer.parseInt(CGPA.getText()), Integer.parseInt(cre.getText()));
            s1 = ug;
        }
        else if(c.equals("PG"))
        {
            PG pg = new PG(c, roll.getText(), name.getText(), dept.getText(), spe.getText(), Integer.parseInt(reg.getText()), Integer.parseInt(CGPA.getText()), Integer.parseInt(cre.getText()), thesis.getText());
            s1 = pg;
        }
        else if(c.equals("UG+PG"))
        {
            UGPG ugPg = new UGPG(c, roll.getText(), name.getText(), dept.getText(), spe.getText(), Integer.parseInt(reg.getText()), Integer.parseInt(CGPA.getText()), Integer.parseInt(cre.getText()), thesis.getText(), Integer.parseInt(year.getText()));
            s1 = ugPg;
        }
        else if(c.equals("PhD"))
        {
            PhD phD = new PhD(c, roll.getText(), name.getText(), Integer.parseInt(reg.getText()), Integer.parseInt(cre.getText()), thesis.getText());
            s1 = phD;
        }
        else if(c.equals("PG+PhD"))
        {
            PGPhD pgPhD = new PGPhD(c, roll.getText(), name.getText(), Integer.parseInt(reg.getText()), Integer.parseInt(CGPA.getText()), Integer.parseInt(cre.getText()), thesis.getText(), Integer.parseInt(year.getText()));
            s1 = pgPhD;
        }
        else
            throw new InvalidCourseException("Invalid Course");
        return s1;
    }
    
    private void courseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseRadioButtonActionPerformed

    private void deptRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptRadioButtonActionPerformed

    private void speRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_speRadioButtonActionPerformed

    private void regRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regRadioButtonActionPerformed

    private void creRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creRadioButtonActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        if(courseRadioButton.isSelected()&&!prevC.equals(course.getText()))
        {String c = course.getText();
        if(c.equals("UG"))
        {
            setSpecialization();
            setThesis();
            setYear();
            checkDept();
            checkCGPA();
        }
        else if(c.equals("PG"))
        {
            setYear();
            checkSpe();
            checkThesis();
            checkDept();
            checkCGPA();
        }
        else if(c.equals("UG+PG"))
        {
            checkYear();
            checkSpe();
            checkThesis();
            checkDept();
            checkCGPA();
        }
        else if(c.equals("PhD"))
        {
            dept.setText("NA");
            dept.setEditable(false);
            CGPA.setText("NA");
            CGPA.setEditable(false);
            setSpecialization();
            setYear();
            checkThesis();
        }
        else if(c.equals("PG+PhD"))
        {
            dept.setText("NA");
            dept.setEditable(false);
            setSpecialization();
            checkYear();
            checkThesis();
            checkCGPA();
        }}
    }//GEN-LAST:event_courseActionPerformed

    private void checkDept()
    {
        if(dept.getText().equals("NA"))
        {    
            dept.setEditable(true);
            dept.setText("");
            deptRadioButton.setSelected(true);
        }
    }
    
    private void checkYear()
    {
        if(year.getText().equals("NA"))
        {    
            year.setEditable(true);
            year.setText("");
            yearRadioButton.setSelected(true);
        }
    }
    
    private void checkCGPA()
    {
        if(CGPA.getText().equals("NA"))
        {    
            CGPA.setEditable(true);
            CGPA.setText("");
            CGPARadioButton.setSelected(true);
        }
    }
    
    private void checkSpe()
    {
        if(spe.getText().equals("NA"))
        {    
            spe.setEditable(true);
            spe.setText("");
            speRadioButton.setSelected(true);
        }
    }
    
    private void checkThesis()
    {
        if(thesis.getText().equals("NA"))
        {    
            thesis.setEditable(true);
            thesis.setText("");
            thesisRadioButton.setSelected(true);
        }
    }
    
    private void setSpecialization()
    {
        spe.setText("NA");
        spe.setEditable(false);
    }
    
    private void setThesis()
    {
        thesis.setText("NA");
        thesis.setEditable(false);
    }
    
    private void setYear()
    {
        year.setText("NA");
        year.setEditable(false);
    }
    
    private void callJFrame1(ListIterator it)
    {
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1(s,it).setVisible(true);
            }
        });
    }
    
    private void setDetails()
    {
        it.previous();
        student s1 = (student)it.next();
        course.setText(s1.getCourse());
        roll.setText(s1.getRollNumber());
        name.setText(s1.getName());
        if(s1.getDept()=="NA")
            dept.setEditable(false);
        dept.setText(s1.getDept());
        if(s1.getSpe()=="NA")
            spe.setEditable(false);
        spe.setText(s1.getDept());
        reg.setText(Integer.toString(s1.getReg()));
        if(s1.getCGPA()==0)
        {
            CGPA.setText("NA");
            CGPA.setEditable(false);
        }
        else
           CGPA.setText(Integer.toString(s1.getCGPA())); 
        cre.setText(Integer.toString(s1.getCredits()));
        if(s1.getThesis()=="NA")
            thesis.setEditable(false);
        thesis.setText(s1.getThesis());
        if(s1.getYear()==0)
        {
            year.setText("NA");
            year.setEditable(false);
        }
        else
            year.setText(Integer.toString(s1.getYear()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_Modify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Modify(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CGPA;
    private javax.swing.JRadioButton CGPARadioButton;
    private javax.swing.JTextField course;
    private javax.swing.JRadioButton courseRadioButton;
    private javax.swing.JTextField cre;
    private javax.swing.JRadioButton creRadioButton;
    private javax.swing.JTextField dept;
    private javax.swing.JRadioButton deptRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton nameRadioButton;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField reg;
    private javax.swing.JRadioButton regRadioButton;
    private javax.swing.JTextField roll;
    private javax.swing.JRadioButton rollRadioButton;
    private javax.swing.JTextField spe;
    private javax.swing.JRadioButton speRadioButton;
    private javax.swing.JTextField thesis;
    private javax.swing.JRadioButton thesisRadioButton;
    private javax.swing.JTextField year;
    private javax.swing.JRadioButton yearRadioButton;
    // End of variables declaration//GEN-END:variables
}
