/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package assignment2;

import java.util.ArrayList;

/**
 *
 * @author Aditi
 */
public class JFrame2 extends javax.swing.JFrame {

    private ArrayList<student> s;
    //private Assignment2 obj;
    
    /** Creates new form JFrame2 */
    public JFrame2(Assignment2 ob) {
        //obj = ob;
        s = ob.getStudents();
        initComponents();
    }
    
    public JFrame2(ArrayList<student> s1)
    {
        s = s1;
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelInput = new javax.swing.JPanel();
        jRadioButtonUG = new javax.swing.JRadioButton();
        selectStudent = new javax.swing.JLabel();
        jRadioButtonPG = new javax.swing.JRadioButton();
        jRadioButtonUGPG = new javax.swing.JRadioButton();
        jRadioButtonPhD = new javax.swing.JRadioButton();
        jRadioButtonPGPhD = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelInput.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "INPUT", 0, 0, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(0, 0, 153))); // NOI18N

        jRadioButtonUG.setText("UG");
        jRadioButtonUG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jRadioButtonUGMousePressed(evt);
            }
        });
        jRadioButtonUG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUGActionPerformed(evt);
            }
        });

        selectStudent.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        selectStudent.setText("Select course type:");

        jRadioButtonPG.setText("PG");
        jRadioButtonPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPGActionPerformed(evt);
            }
        });

        jRadioButtonUGPG.setText("UG+PG");
        jRadioButtonUGPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUGPGActionPerformed(evt);
            }
        });

        jRadioButtonPhD.setText("PhD");
        jRadioButtonPhD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPhDActionPerformed(evt);
            }
        });

        jRadioButtonPGPhD.setText("PG+PhD");
        jRadioButtonPGPhD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPGPhDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelInputLayout = new javax.swing.GroupLayout(PanelInput);
        PanelInput.setLayout(PanelInputLayout);
        PanelInputLayout.setHorizontalGroup(
            PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPGPhD)
                    .addComponent(jRadioButtonPhD)
                    .addComponent(jRadioButtonUGPG)
                    .addComponent(jRadioButtonPG)
                    .addComponent(jRadioButtonUG)
                    .addComponent(selectStudent))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        PanelInputLayout.setVerticalGroup(
            PanelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInputLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(selectStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonUG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonUGPG)
                .addGap(3, 3, 3)
                .addComponent(jRadioButtonPhD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButtonPGPhD)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(PanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(PanelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonUGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUGActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Student("UG",s).setVisible(true);
                
            }
        });
    }//GEN-LAST:event_jRadioButtonUGActionPerformed

    private void jRadioButtonUGPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUGPGActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Student("UG+PG",s).setVisible(true);
            }
        });
    }//GEN-LAST:event_jRadioButtonUGPGActionPerformed

    private void jRadioButtonPhDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPhDActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Student("PhD",s).setVisible(true);
            }
        });
    }//GEN-LAST:event_jRadioButtonPhDActionPerformed

    private void jRadioButtonUGMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonUGMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonUGMousePressed

    private void jRadioButtonPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPGActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Student("PG",s).setVisible(true);
            }
        });
    }//GEN-LAST:event_jRadioButtonPGActionPerformed

    private void jRadioButtonPGPhDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPGPhDActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_Student("PG+PhD",s).setVisible(true);
            }
        });
    }//GEN-LAST:event_jRadioButtonPGPhDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame2(new Assignment2()).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelInput;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRadioButtonPG;
    private javax.swing.JRadioButton jRadioButtonPGPhD;
    private javax.swing.JRadioButton jRadioButtonPhD;
    private javax.swing.JRadioButton jRadioButtonUG;
    private javax.swing.JRadioButton jRadioButtonUGPG;
    private javax.swing.JLabel selectStudent;
    // End of variables declaration//GEN-END:variables

}
